services:
  db:
    image: postgres:16-alpine
    container_name: deviny-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: DevinyDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: .
    container_name: deviny_api
    depends_on:
      - db
    restart: always
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__DefaultConnection: Host=db;Port=5432;Database=DevinyDB;Username=postgres;Password=postgres;Pooling=true;Minimum Pool Size=2;Maximum Pool Size=50;Connection Idle Lifetime=300;Keepalive=30;Timeout=15
      ClientAppUrl: https://app.deviny.me
      CorsOrigins: "https://app.deviny.me;https://deviny.me;https://www.deviny.me"
      FileStorage__BaseUrl: https://api.deviny.me
    ports:
      - "8080:8080"

volumes:
  postgres_data: